title = "Csaba Okrona"
baseURL = "https://csa.ba/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Berlin, Germany"
email = "contact@ochronus.com"
favicon = "/favicon.ico"
firstName = "Csaba"
lastName = "Okrona"
profileImage = "img/ochronus-768x893.jpeg"
showEducation = true
showExperience = true
showOpenSource = true
showProjects = true
showPublications = true
showQr = true
showSkills = true

[params.google]


[[params.handles]]
link = "https://www.linkedin.com/in/ochronus/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/ochronus/"
name = "GitHub"


[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"